### ISSUE TITLE
部署合约报错

### ISSUE THREAD

**Issue by guotie** [ccyanxyz/uniswap-arbitrage-analysis#5]
部署合约报错：

```
2_deploy_contracts.js
=====================

C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\commands.bundled.js:487817
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for Flashloan from any sources
    at Resolver.require (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\resolver\dist\lib\resolver.js:44:1)
    at Object.require (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:172:1)
    at ResolverIntercept.require (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\ResolverIntercept.js:22:1)
    at D:\guotie\dexcex\uniswap-arbitrage-analysis\src\contract\migrations\2_deploy_contracts.js:1:29
    at Script.runInContext (vm.js:131:20)
    at Script.runInNewContext (vm.js:137:17)
    at Object.file (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\require\require.js:94:1)
    at Migration._load (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:43:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration.run (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:171:1)
    at Object.runMigrations (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.run (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:87:1)
    at runMigrations (C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:269:1)
    at C:\Users\guotie\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:231:1
Truffle v5.1.54 (core: 5.1.54)
Node v12.16.1
```

**Comment by zeoio** [comment]
我也遇到了
